services:
  - type: web
    name: tommymoran-chatbot
    env: python
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: python -m gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false 